[identities]
root = "age1xzkgqkethzqdkxck5dyykzgx8n6y8wmy96d3jm77jzgw9g9yx4kqppzfg2"
ldesgoui = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK25ea20daUVvmTPmUL1nF/0DXEz/7tPBXOSerQNTf6+"
game-1 = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII0gx4mLAHbzQ2HM+4KbHYxi6zh9ZX8/J12cQ/qmQJ4D"
game-2 = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL5fiRhJPhLslM6OMsGWmrDNE/O366CcxKlV6NEPD2CM"
game-3 = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHRN/RbelaVSVezFG6IYDqk+bafFkRY9ZLPiKBuHnuvE"
game-4 = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIT1AR2dVkpPI3qiIhoLSnW5HzC89QAyG3GKO3uJlXbe"
game-5 = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMTxealSMTzNxKoxfahAthT1MTRj8egoD8dMPMBy3wLs"
game-6 = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIClNcVNvee749fRDbMgsbUh4NiuNvuTKKIj8SbrrtY0T"

[groups]
admins = ["root", "ldesgoui"]
servers = ["game-1", "game-2", "game-3", "game-4", "game-5", "game-6"]

[[paths]]
glob = "root-password.age"
groups = ["admins"]

[[paths]]
glob = "ssh/*.age"
groups = ["admins"]

[[paths]]
glob = "wg/game-1.age"
groups = ["admins"]
identities = ["game-1"]

[[paths]]
glob = "wg/game-2.age"
groups = ["admins"]
identities = ["game-2"]

[[paths]]
glob = "wg/game-3.age"
groups = ["admins"]
identities = ["game-3"]

[[paths]]
glob = "wg/game-4.age"
groups = ["admins"]
identities = ["game-4"]

[[paths]]
glob = "wg/game-5.age"
groups = ["admins"]
identities = ["game-5"]

[[paths]]
glob = "wg/game-6.age"
groups = ["admins"]
identities = ["game-6"]

[[paths]]
glob = "cfg/*.age"
groups = ["admins", "servers"]

[[paths]]
glob = "passwords.json.age"
groups = ["admins", "servers"]

[[paths]]
glob = "gandi-creds.age"
groups = ["admins"]
identities = ["game-1"]
